Add details of vulnerability disclosure program
alphagov/.github pull request #9
Opened 2021-07-21 14:42 UTC by pritchyspritch

2021-07-21 15:16 UTC, gabrielcurrie requested changes
Comments in line, sorry I couldn't get the "suggest changes" function to work!

2021-07-21 15:16 UTC, gabrielcurrie commented on SECURITY.md
> +GDS is an advocate of responsible vulnerability disclosure. If you’ve found a vulnerability, we would like to know so we can fix it. Quick links can be found at our [security.txt](https://vdp.cabinet
Suggest being a bit clearer on what we mean by "quick links", for example, by saying something like...

`This notice provides details for how you can let us know about vulnerabilities, or alternatively you can view our [security.txt](https://vdp.cabinetoffice.gov.uk/.well-known/security.txt) file which contains quick links to contact us.`

2021-07-21 15:16 UTC, gabrielcurrie commented on SECURITY.md
> +- screenshots or logs if you have them
Suggested wording tweak:

`screenshots or logs showing the exploitation of the vulnerability`

2021-07-21 15:16 UTC, gabrielcurrie commented on SECURITY.md
> +- screenshots or logs if you have them
Could we move the optional items to another list after this, headed with something like `If you are able to, please also include:`

2021-07-21 15:16 UTC, gabrielcurrie commented on SECURITY.md
>  - optionally the type of vulnerability and any related [OWASP category]
Suggested wording tweak:

`the type of vulnerability, for example, the [OWASP category](https://owasp.org/www-community/vulnerabilities/)`

Also suggest we move "any related" into a separate line?

2021-07-21 15:16 UTC, gabrielcurrie commented on SECURITY.md
> +You can [report a vulnerability to GDS using HackerOne](https://hackerone.com/44c348eb-e030-4273-b445-d4a2f6f83ba8/embedded_submissions/new), please include:
Suggested wording change:

```
You can report a vulnerability to GDS through our vulnerability disclosure programme at [HackerOne](https://hackerone.com/44c348eb-e030-4273-b445-d4a2f6f83ba8/embedded_submissions/new). Alternatively, you can send an email to [disclosure@digital.cabinet-office.gov.uk]; if you do this you may get a response from ZenDesk, which is our ticketing system. 

When reporting a vulnerability to us, please include:
```

2021-07-21 15:16 UTC, gabrielcurrie commented on SECURITY.md
> +- demand money to disclose a vulnerability
These are less things that fall in/out of scope, and more the things that we don't want people to do to find a vulnerability, or do when they find a vulnerability. Agree they should be in here, but can we tweak wording to be clearer?

2021-07-21 15:16 UTC, gabrielcurrie commented on SECURITY.md
> +Then you can still [reach out via email](disclosure@digital.cabinet-office.gov.uk) or using the [GOV.UK contact form](https://www.gov.uk/contact/govuk).
It feels like this should go into the top section on Reporting a Vulnerability, rather than this section on scope?

2021-07-21 16:07 UTC, gabrielcurrie approved these changes
Looks good!

2021-07-22 10:05 UTC, akinnane approved these changes

2021-07-22 10:53 UTC, merged